# Generated by Django 5.0.2 on 2024-03-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLink',
            fields=[
                ('linkID', models.IntegerField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('timeCreated', models.TimeField()),
            ],
        ),
    ]
