# Generated by Django 5.0.2 on 2024-03-17 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailLinkDB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emaillink',
            name='timeCreated',
        ),
    ]
