# Generated by Django 5.0.2 on 2024-02-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('info', models.CharField(max_length=256)),
                ('gpsLat', models.FloatField()),
                ('gpsLon', models.FloatField()),
                ('radius', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=256)),
                ('answer0', models.CharField(max_length=64)),
                ('answer1', models.CharField(max_length=64)),
                ('answer2', models.CharField(max_length=64)),
                ('correctAnswer', models.SmallIntegerField()),
                ('score', models.IntegerField()),
                ('location', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='contentDB.location')),
            ],
        ),
    ]
