# Generated by Django 5.0.2 on 2024-02-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contentDB', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='gpsLat',
            new_name='gps_lat',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='gpsLon',
            new_name='gps_long',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='correctAnswer',
            new_name='correct_answer',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='score',
            new_name='points',
        ),
    ]
