# Generated by Django 5.0.2 on 2024-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contentDB', '0002_rename_gpslat_location_gps_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='location',
            field=models.IntegerField(),
        ),
    ]
