# Generated by Django 5.0.1 on 2024-03-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contentDB", "0003_alter_quiz_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task", models.CharField(max_length=256)),
                ("points", models.IntegerField()),
            ],
        ),
    ]
