# Generated by Django 5.0.2 on 2024-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0002_rename_accesslevel_user_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='recovery_email',
            field=models.EmailField(max_length=254),
        ),
    ]
