# Generated by Django 3.2.12 on 2024-03-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDB', '0003_alter_user_recovery_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTargetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.IntegerField()),
                ('location', models.IntegerField()),
            ],
        ),
    ]
